# Generated by Django 5.2.8 on 2025-12-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_verificacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('repartidor', 'Repartidor'), ('admin', 'Administrador')], default='estudiante', max_length=50),
        ),
    ]
