# Generated by Django 5.2.8 on 2025-12-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_estado_verificacion_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
