# Generated by Django 5.2.8 on 2025-11-11 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('codigoPedido', models.AutoField(primary_key=True, serialize=False)),
                ('num_whats', models.CharField(max_length=12)),
                ('descripcion', models.TextField()),
                ('punto_origen_id', models.IntegerField()),
                ('punto_desitno_id', models.IntegerField()),
                ('estado', models.CharField(choices=[('Publicado', 'Publicado'), ('Aceptado', 'Aceptado'), ('Entregado', 'Entregado')], max_length=50)),
                ('fechaInicial', models.DateTimeField()),
                ('horaDeseada', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
                ('costoEnvio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_realizados', to=settings.AUTH_USER_MODEL)),
                ('idRepartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_entregados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
