# Generated by Django 5.2.8 on 2025-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('codigoPedido', models.AutoField(primary_key=True, serialize=False)),
                ('num_whats', models.CharField(max_length=12)),
                ('descripcion', models.TextField()),
                ('punto_origen_id', models.CharField(max_length=255)),
                ('punto_destino_id', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Publicado', 'Publicado'), ('Aceptado', 'Aceptado'), ('Entregado', 'Entregado')], default='Publicado', max_length=50)),
                ('fechaInicial', models.DateTimeField(auto_now_add=True)),
                ('horaDeseada', models.DateTimeField(blank=True, null=True)),
                ('fechaFinal', models.DateTimeField(blank=True, null=True)),
                ('costoEnvio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('archivo_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('formato_color', models.CharField(blank=True, choices=[('Blanco y Negro', 'Blanco y Negro'), ('Color', 'Color')], max_length=50, null=True)),
            ],
        ),
    ]
