# Generated by Django 5.2.8 on 2025-12-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='punto_desitno_id',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='punto_origen_id',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='codigo_entrega',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='punto_destino',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='punto_origen',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
