# Generated by Django 5.2.8 on 2025-12-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='codigo_entrega',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('Publicado', 'Publicado'), ('Aceptado', 'Aceptado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Publicado', max_length=50),
        ),
    ]
