# Generated by Django 5.2.8 on 2025-12-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedidos_punto_desitno_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='archivo_pdf',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='formato_color',
            field=models.CharField(blank=True, choices=[('Blanco y Negro', 'Blanco y Negro'), ('Color', 'Color')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='codigo_entrega',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('Publicado', 'Publicado'), ('Aceptado', 'Aceptado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Publicado', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fechaInicial',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='horaDeseada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
