# Generated by Django 5.2.8 on 2025-12-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidos_archivo_pdf_pedidos_formato_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='costoEnvio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
