# Generated by Django 5.2.8 on 2025-12-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidos_codigo_entrega_alter_pedidos_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='punto_destino_id',
            new_name='punto_destino',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='punto_origen_id',
            new_name='punto_origen',
        ),
    ]
